image: gitlab.int.toradex.com:4567/rd/torizon-core/debian/debian-package-devel/arm64v8-debian-package-devel:buster

variables:
        DEBFULLNAME: "Eugene Nuribekov"
        DEBEMAIL: "eugene.nuribekov@toradex.com"

build:
  script:
  # Remove all downloaded/generated artifacts 
  - rm -rf debs
  - rm -rf gpu-core
  - ./for_every_package.sh ../clean.sh
  # Download and unpack archive from the NXP repo
  - ./get_binaries.sh
  # Distribute .so from big pile to separate package directories
  - ./for_every_package.sh ../copy_binaries.sh
  # Debianazing sources and build debs 
  - ./for_every_package.sh ../build_deb.sh 
  # Copy packages to single direcory
  - mkdir -p debs
  - ./for_every_package.sh ../copy_deb.sh

  artifacts:
          paths: 
          - debs
